// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lexer.flex

// Main code
import obj.token;
// This object will contain the token name and line where is located


@SuppressWarnings("fallthrough")
public class absScanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\0"+
    "\1\5\4\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\12\17\1\20\1\21\1\22\1\23"+
    "\1\24\2\0\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\45\1\56\1\0\1\57\1\60"+
    "\1\45\1\0\4\61\1\62\1\61\21\45\1\63\2\45"+
    "\1\64\1\0\1\65\7\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\2\1\3\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\25\21\1\22\1\23\1\24\1\1"+
    "\1\0\1\25\1\2\2\0\1\26\1\27\1\30\3\0"+
    "\1\31\1\32\1\33\13\21\1\34\10\21\1\35\1\21"+
    "\1\36\5\21\1\37\1\40\7\21\1\41\10\21\1\0"+
    "\1\42\2\43\1\0\1\13\1\0\2\13\1\21\1\44"+
    "\1\21\1\45\6\21\1\46\2\21\1\47\3\21\1\50"+
    "\4\21\1\51\1\21\1\52\1\53\1\54\6\21\1\55"+
    "\1\56\1\57\6\21\1\60\3\21\1\61\1\62\4\21"+
    "\1\63\1\64\3\21\1\65\1\21\1\66\3\21\1\67"+
    "\13\21\1\70\1\71\1\72\1\21\1\73\2\21\1\74"+
    "\1\21\1\75\1\76\1\21\1\77\3\21\1\100\5\21"+
    "\1\101\7\21\1\102\5\21\1\103\4\21\1\104\2\21"+
    "\1\105\1\106\2\21\1\107\1\110\1\111\5\21\1\112"+
    "\4\21\1\113\1\21\1\114\1\115\2\21\1\116\1\117"+
    "\7\21\1\120\1\121\1\122\1\21\1\123\1\21\1\124"+
    "\3\21\1\125";

  private static int [] zzUnpackAction() {
    int [] result = new int[275];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\66\0\u0144"+
    "\0\u017a\0\66\0\u01b0\0\66\0\66\0\u01e6\0\66\0\66"+
    "\0\u021c\0\66\0\u0252\0\u0288\0\u02be\0\u02f4\0\u032a\0\u0360"+
    "\0\u0396\0\u03cc\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da\0\u0510"+
    "\0\u0546\0\u057c\0\u05b2\0\u05e8\0\u061e\0\u0654\0\u068a\0\u06c0"+
    "\0\66\0\66\0\66\0\u06f6\0\242\0\66\0\u072c\0\u0762"+
    "\0\u0798\0\66\0\66\0\66\0\u07ce\0\u0804\0\u083a\0\66"+
    "\0\66\0\66\0\u0870\0\u08a6\0\u08dc\0\u0912\0\u0948\0\u097e"+
    "\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2\0\u0af8\0\u0b2e"+
    "\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c\0\u0c72\0\u0402\0\u0ca8"+
    "\0\u0cde\0\u0d14\0\u0d4a\0\u0d80\0\u0db6\0\u0dec\0\u0402\0\u0402"+
    "\0\u0e22\0\u0e58\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30\0\u0f66\0\u0402"+
    "\0\u0f9c\0\u0fd2\0\u1008\0\u103e\0\u1074\0\u10aa\0\u10e0\0\u1116"+
    "\0\u06f6\0\66\0\154\0\66\0\u114c\0\u1182\0\u11b8\0\u11b8"+
    "\0\u083a\0\u11ee\0\u0402\0\u1224\0\u0402\0\u125a\0\u1290\0\u12c6"+
    "\0\u12fc\0\u1332\0\u1368\0\u0402\0\u139e\0\u13d4\0\u0402\0\u140a"+
    "\0\u1440\0\u1476\0\u14ac\0\u14e2\0\u1518\0\u154e\0\u1584\0\u15ba"+
    "\0\u15f0\0\u0402\0\u0402\0\u0402\0\u1626\0\u165c\0\u1692\0\u16c8"+
    "\0\u16fe\0\u1734\0\u0402\0\u0402\0\u0402\0\u176a\0\u17a0\0\u17d6"+
    "\0\u180c\0\u1842\0\u1878\0\u0402\0\u18ae\0\u18e4\0\u191a\0\u0402"+
    "\0\u0798\0\u1950\0\u1986\0\u19bc\0\u19f2\0\u0402\0\u0402\0\u1a28"+
    "\0\u1a5e\0\u1a94\0\u0402\0\u1aca\0\u0402\0\u1b00\0\u1b36\0\u1b6c"+
    "\0\u0402\0\u1ba2\0\u1bd8\0\u1c0e\0\u1c44\0\u1c7a\0\u1cb0\0\u1ce6"+
    "\0\u1d1c\0\u1d52\0\u1d88\0\u1dbe\0\u0402\0\u0402\0\u0402\0\u1df4"+
    "\0\u0402\0\u1e2a\0\u1e60\0\u0402\0\u1e96\0\u0402\0\u0402\0\u1ecc"+
    "\0\u1f02\0\u1f38\0\u1f6e\0\u1fa4\0\u0402\0\u1fda\0\u2010\0\u2046"+
    "\0\u207c\0\u20b2\0\u0402\0\u20e8\0\u211e\0\u2154\0\u218a\0\u21c0"+
    "\0\u21f6\0\u222c\0\u0402\0\u2262\0\u2298\0\u22ce\0\u2304\0\u233a"+
    "\0\u0402\0\u2370\0\u23a6\0\u23dc\0\u2412\0\u0402\0\u2448\0\u247e"+
    "\0\u0402\0\u0402\0\u24b4\0\u24ea\0\u0402\0\u0402\0\u0402\0\u2520"+
    "\0\u2556\0\u258c\0\u25c2\0\u25f8\0\u0402\0\u262e\0\u2664\0\u269a"+
    "\0\u26d0\0\u0402\0\u2706\0\u0402\0\u0402\0\u273c\0\u2772\0\u0402"+
    "\0\u0402\0\u27a8\0\u27de\0\u2814\0\u284a\0\u2880\0\u28b6\0\u28ec"+
    "\0\u0402\0\u0402\0\u0402\0\u2922\0\u0402\0\u2958\0\u0402\0\u298e"+
    "\0\u29c4\0\u29fa\0\u0402";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[275];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\2\33\1\35\1\36"+
    "\1\37\1\40\1\41\1\33\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\33\1\51\1\52\1\53\3\33"+
    "\1\54\1\2\67\0\2\3\1\0\1\3\1\0\1\3"+
    "\61\0\1\55\2\0\1\56\11\0\1\55\5\0\31\55"+
    "\3\0\3\55\3\0\1\3\1\57\1\0\1\3\1\0"+
    "\1\3\10\0\1\60\5\0\31\60\3\0\3\60\13\0"+
    "\1\61\65\0\1\62\66\0\1\63\67\0\1\64\66\0"+
    "\1\65\1\0\1\16\11\0\1\66\22\0\1\67\5\0"+
    "\1\66\1\67\25\0\1\70\1\71\64\0\1\72\61\0"+
    "\1\33\5\0\1\33\1\73\13\33\1\74\3\33\1\75"+
    "\1\76\6\33\3\0\3\33\21\0\1\33\5\0\4\33"+
    "\1\77\11\33\1\100\12\33\3\0\3\33\21\0\1\33"+
    "\5\0\1\101\6\33\1\102\6\33\1\103\12\33\3\0"+
    "\3\33\21\0\1\33\5\0\4\33\1\104\3\33\1\105"+
    "\5\33\1\106\12\33\3\0\3\33\21\0\1\33\5\0"+
    "\13\33\1\107\1\33\1\110\11\33\1\111\1\33\3\0"+
    "\3\33\21\0\1\33\5\0\10\33\1\112\2\33\1\113"+
    "\2\33\1\114\5\33\1\115\4\33\3\0\3\33\21\0"+
    "\1\33\5\0\16\33\1\116\12\33\3\0\3\33\21\0"+
    "\1\33\5\0\31\33\3\0\3\33\21\0\1\33\5\0"+
    "\5\33\1\117\6\33\1\120\1\121\13\33\3\0\3\33"+
    "\21\0\1\33\5\0\1\122\30\33\3\0\3\33\21\0"+
    "\1\33\5\0\16\33\1\123\12\33\3\0\3\33\21\0"+
    "\1\33\5\0\10\33\1\124\5\33\1\125\12\33\3\0"+
    "\3\33\21\0\1\33\5\0\1\33\1\126\3\33\1\127"+
    "\13\33\1\130\7\33\3\0\3\33\21\0\1\33\5\0"+
    "\1\131\20\33\1\132\7\33\3\0\3\33\21\0\1\33"+
    "\5\0\4\33\1\133\24\33\3\0\3\33\21\0\1\33"+
    "\5\0\4\33\1\134\2\33\1\135\13\33\1\136\5\33"+
    "\3\0\3\33\21\0\1\33\5\0\7\33\1\137\6\33"+
    "\1\140\11\33\1\141\3\0\3\33\21\0\1\33\5\0"+
    "\15\33\1\142\4\33\1\143\6\33\3\0\3\33\21\0"+
    "\1\33\5\0\1\144\7\33\1\145\20\33\3\0\3\33"+
    "\21\0\1\33\5\0\7\33\1\146\1\147\20\33\3\0"+
    "\3\33\21\0\1\33\5\0\16\33\1\150\12\33\3\0"+
    "\3\33\2\0\65\151\1\152\1\0\2\3\1\0\1\3"+
    "\1\0\1\153\65\0\1\154\57\0\2\61\3\0\4\61"+
    "\1\155\54\61\17\0\1\156\60\0\1\157\1\0\1\157"+
    "\2\0\1\160\65\0\1\161\5\0\6\161\26\0\2\161"+
    "\22\0\1\33\5\0\22\33\1\162\6\33\3\0\3\33"+
    "\21\0\1\33\5\0\3\33\1\163\25\33\3\0\3\33"+
    "\21\0\1\33\5\0\21\33\1\164\7\33\3\0\3\33"+
    "\21\0\1\33\5\0\14\33\1\165\14\33\3\0\3\33"+
    "\21\0\1\33\5\0\6\33\1\166\22\33\3\0\3\33"+
    "\21\0\1\33\5\0\16\33\1\167\12\33\3\0\3\33"+
    "\21\0\1\33\5\0\22\33\1\170\6\33\3\0\3\33"+
    "\21\0\1\33\5\0\1\171\30\33\3\0\3\33\21\0"+
    "\1\33\5\0\15\33\1\172\13\33\3\0\3\33\21\0"+
    "\1\33\5\0\22\33\1\173\6\33\3\0\3\33\21\0"+
    "\1\33\5\0\25\33\1\174\3\33\3\0\3\33\21\0"+
    "\1\33\5\0\26\33\1\175\2\33\3\0\3\33\21\0"+
    "\1\33\5\0\22\33\1\176\6\33\3\0\3\33\21\0"+
    "\1\33\5\0\3\33\1\177\25\33\3\0\3\33\21\0"+
    "\1\33\5\0\23\33\1\200\5\33\3\0\3\33\21\0"+
    "\1\33\5\0\13\33\1\201\15\33\3\0\3\33\21\0"+
    "\1\33\5\0\16\33\1\202\12\33\3\0\3\33\21\0"+
    "\1\33\5\0\21\33\1\203\7\33\3\0\3\33\21\0"+
    "\1\33\5\0\15\33\1\204\13\33\3\0\3\33\21\0"+
    "\1\33\5\0\23\33\1\205\5\33\3\0\3\33\21\0"+
    "\1\33\5\0\17\33\1\206\11\33\3\0\3\33\21\0"+
    "\1\33\5\0\13\33\1\207\7\33\1\210\5\33\3\0"+
    "\3\33\21\0\1\33\5\0\1\33\1\211\27\33\3\0"+
    "\3\33\21\0\1\33\5\0\3\33\1\212\25\33\3\0"+
    "\3\33\21\0\1\33\5\0\13\33\1\213\15\33\3\0"+
    "\3\33\21\0\1\33\5\0\23\33\1\214\5\33\3\0"+
    "\3\33\21\0\1\33\5\0\11\33\1\215\17\33\3\0"+
    "\3\33\21\0\1\33\5\0\2\33\1\216\26\33\3\0"+
    "\3\33\21\0\1\33\5\0\10\33\1\217\5\33\1\220"+
    "\12\33\3\0\3\33\21\0\1\33\5\0\2\33\1\221"+
    "\14\33\1\222\11\33\3\0\3\33\21\0\1\33\5\0"+
    "\23\33\1\223\5\33\3\0\3\33\21\0\1\33\5\0"+
    "\13\33\1\224\5\33\1\225\7\33\3\0\3\33\21\0"+
    "\1\33\5\0\21\33\1\226\7\33\3\0\3\33\21\0"+
    "\1\33\5\0\4\33\1\227\24\33\3\0\3\33\21\0"+
    "\1\33\5\0\17\33\1\230\11\33\3\0\3\33\21\0"+
    "\1\33\5\0\10\33\1\231\12\33\1\232\5\33\3\0"+
    "\3\33\21\0\1\33\5\0\4\33\1\233\24\33\3\0"+
    "\3\33\21\0\1\33\5\0\21\33\1\234\7\33\3\0"+
    "\3\33\21\0\1\33\5\0\21\33\1\235\7\33\3\0"+
    "\3\33\21\0\1\33\5\0\10\33\1\236\20\33\3\0"+
    "\3\33\21\0\1\33\5\0\23\33\1\237\5\33\3\0"+
    "\3\33\21\0\1\33\5\0\21\33\1\240\7\33\3\0"+
    "\3\33\2\0\2\61\3\0\3\61\1\241\1\155\54\61"+
    "\17\0\1\156\11\0\1\66\30\0\1\66\22\0\1\160"+
    "\65\0\1\33\5\0\16\33\1\242\12\33\3\0\3\33"+
    "\21\0\1\33\5\0\1\243\30\33\3\0\3\33\21\0"+
    "\1\33\5\0\10\33\1\244\20\33\3\0\3\33\21\0"+
    "\1\33\5\0\13\33\1\245\15\33\3\0\3\33\21\0"+
    "\1\33\5\0\4\33\1\246\24\33\3\0\3\33\21\0"+
    "\1\33\5\0\21\33\1\247\7\33\3\0\3\33\21\0"+
    "\1\33\5\0\22\33\1\250\6\33\3\0\3\33\21\0"+
    "\1\33\5\0\23\33\1\251\5\33\3\0\3\33\21\0"+
    "\1\33\5\0\15\33\1\252\13\33\3\0\3\33\21\0"+
    "\1\33\5\0\4\33\1\253\24\33\3\0\3\33\21\0"+
    "\1\33\5\0\4\33\1\254\24\33\3\0\3\33\21\0"+
    "\1\33\5\0\4\33\1\255\24\33\3\0\3\33\21\0"+
    "\1\33\5\0\1\256\30\33\3\0\3\33\21\0\1\33"+
    "\5\0\26\33\1\257\2\33\3\0\3\33\21\0\1\33"+
    "\5\0\2\33\1\260\26\33\3\0\3\33\21\0\1\33"+
    "\5\0\16\33\1\261\12\33\3\0\3\33\21\0\1\33"+
    "\5\0\13\33\1\262\15\33\3\0\3\33\21\0\1\33"+
    "\5\0\10\33\1\263\20\33\3\0\3\33\21\0\1\33"+
    "\5\0\4\33\1\264\24\33\3\0\3\33\21\0\1\33"+
    "\5\0\4\33\1\265\24\33\3\0\3\33\21\0\1\33"+
    "\5\0\4\33\1\266\24\33\3\0\3\33\21\0\1\33"+
    "\5\0\12\33\1\267\16\33\3\0\3\33\21\0\1\33"+
    "\5\0\25\33\1\270\3\33\3\0\3\33\21\0\1\33"+
    "\5\0\2\33\1\271\26\33\3\0\3\33\21\0\1\33"+
    "\5\0\16\33\1\272\12\33\3\0\3\33\21\0\1\33"+
    "\5\0\4\33\1\273\24\33\3\0\3\33\21\0\1\33"+
    "\5\0\10\33\1\274\20\33\3\0\3\33\21\0\1\33"+
    "\5\0\15\33\1\275\13\33\3\0\3\33\21\0\1\33"+
    "\5\0\4\33\1\276\24\33\3\0\3\33\21\0\1\33"+
    "\5\0\23\33\1\277\5\33\3\0\3\33\21\0\1\33"+
    "\5\0\10\33\1\300\20\33\3\0\3\33\21\0\1\33"+
    "\5\0\22\33\1\301\6\33\3\0\3\33\21\0\1\33"+
    "\5\0\23\33\1\302\5\33\3\0\3\33\21\0\1\33"+
    "\5\0\13\33\1\303\15\33\3\0\3\33\21\0\1\33"+
    "\5\0\7\33\1\304\21\33\3\0\3\33\21\0\1\33"+
    "\5\0\13\33\1\305\15\33\3\0\3\33\21\0\1\33"+
    "\5\0\30\33\1\306\3\0\3\33\21\0\1\33\5\0"+
    "\15\33\1\307\13\33\3\0\3\33\21\0\1\33\5\0"+
    "\4\33\1\310\24\33\3\0\3\33\21\0\1\33\5\0"+
    "\23\33\1\311\5\33\3\0\3\33\21\0\1\33\5\0"+
    "\21\33\1\312\7\33\3\0\3\33\21\0\1\33\5\0"+
    "\23\33\1\313\5\33\3\0\3\33\21\0\1\33\5\0"+
    "\21\33\1\314\7\33\3\0\3\33\21\0\1\33\5\0"+
    "\23\33\1\315\5\33\3\0\3\33\21\0\1\33\5\0"+
    "\1\316\30\33\3\0\3\33\21\0\1\33\5\0\23\33"+
    "\1\317\5\33\3\0\3\33\21\0\1\33\5\0\4\33"+
    "\1\320\24\33\3\0\3\33\21\0\1\33\5\0\15\33"+
    "\1\321\13\33\3\0\3\33\21\0\1\33\5\0\21\33"+
    "\1\322\7\33\3\0\3\33\21\0\1\33\5\0\13\33"+
    "\1\323\15\33\3\0\3\33\21\0\1\33\5\0\2\33"+
    "\1\324\26\33\3\0\3\33\21\0\1\33\5\0\4\33"+
    "\1\325\24\33\3\0\3\33\21\0\1\33\5\0\1\326"+
    "\30\33\3\0\3\33\21\0\1\33\5\0\4\33\1\327"+
    "\24\33\3\0\3\33\21\0\1\33\5\0\21\33\1\330"+
    "\7\33\3\0\3\33\21\0\1\33\5\0\1\331\30\33"+
    "\3\0\3\33\21\0\1\33\5\0\15\33\1\332\13\33"+
    "\3\0\3\33\21\0\1\33\5\0\13\33\1\333\15\33"+
    "\3\0\3\33\21\0\1\33\5\0\24\33\1\334\4\33"+
    "\3\0\3\33\21\0\1\33\5\0\4\33\1\304\24\33"+
    "\3\0\3\33\21\0\1\33\5\0\24\33\1\335\4\33"+
    "\3\0\3\33\21\0\1\33\5\0\1\336\30\33\3\0"+
    "\3\33\21\0\1\33\5\0\21\33\1\337\7\33\3\0"+
    "\3\33\21\0\1\33\5\0\24\33\1\340\4\33\3\0"+
    "\3\33\21\0\1\33\5\0\16\33\1\341\12\33\3\0"+
    "\3\33\21\0\1\33\5\0\15\33\1\342\13\33\3\0"+
    "\3\33\21\0\1\33\5\0\21\33\1\343\7\33\3\0"+
    "\3\33\21\0\1\33\5\0\10\33\1\344\20\33\3\0"+
    "\3\33\21\0\1\33\5\0\14\33\1\345\14\33\3\0"+
    "\3\33\21\0\1\33\5\0\4\33\1\346\24\33\3\0"+
    "\3\33\21\0\1\33\5\0\5\33\1\347\13\33\1\350"+
    "\7\33\3\0\3\33\21\0\1\33\5\0\23\33\1\351"+
    "\5\33\3\0\3\33\21\0\1\33\5\0\3\33\1\352"+
    "\25\33\3\0\3\33\21\0\1\33\5\0\23\33\1\353"+
    "\5\33\3\0\3\33\21\0\1\33\5\0\3\33\1\354"+
    "\25\33\3\0\3\33\21\0\1\33\5\0\3\33\1\355"+
    "\25\33\3\0\3\33\21\0\1\33\5\0\23\33\1\356"+
    "\5\33\3\0\3\33\21\0\1\33\5\0\6\33\1\357"+
    "\22\33\3\0\3\33\21\0\1\33\5\0\1\360\30\33"+
    "\3\0\3\33\21\0\1\33\5\0\23\33\1\361\5\33"+
    "\3\0\3\33\21\0\1\33\5\0\15\33\1\315\13\33"+
    "\3\0\3\33\21\0\1\33\5\0\24\33\1\362\4\33"+
    "\3\0\3\33\21\0\1\33\5\0\2\33\1\363\26\33"+
    "\3\0\3\33\21\0\1\33\5\0\1\364\30\33\3\0"+
    "\3\33\21\0\1\33\5\0\3\33\1\365\25\33\3\0"+
    "\3\33\21\0\1\33\5\0\16\33\1\366\12\33\3\0"+
    "\3\33\21\0\1\33\5\0\4\33\1\367\24\33\3\0"+
    "\3\33\21\0\1\33\5\0\1\370\30\33\3\0\3\33"+
    "\21\0\1\33\5\0\24\33\1\371\4\33\3\0\3\33"+
    "\21\0\1\33\5\0\4\33\1\372\24\33\3\0\3\33"+
    "\21\0\1\33\5\0\24\33\1\373\4\33\3\0\3\33"+
    "\21\0\1\33\5\0\13\33\1\374\15\33\3\0\3\33"+
    "\21\0\1\33\5\0\4\33\1\375\24\33\3\0\3\33"+
    "\21\0\1\33\5\0\2\33\1\376\26\33\3\0\3\33"+
    "\21\0\1\33\5\0\23\33\1\377\5\33\3\0\3\33"+
    "\21\0\1\33\5\0\13\33\1\u0100\15\33\3\0\3\33"+
    "\21\0\1\33\5\0\15\33\1\u0101\13\33\3\0\3\33"+
    "\21\0\1\33\5\0\15\33\1\u0102\13\33\3\0\3\33"+
    "\21\0\1\33\5\0\2\33\1\u0103\26\33\3\0\3\33"+
    "\21\0\1\33\5\0\17\33\1\u0104\11\33\3\0\3\33"+
    "\21\0\1\33\5\0\21\33\1\u0105\7\33\3\0\3\33"+
    "\21\0\1\33\5\0\23\33\1\u0106\5\33\3\0\3\33"+
    "\21\0\1\33\5\0\16\33\1\u0107\12\33\3\0\3\33"+
    "\21\0\1\33\5\0\23\33\1\u0108\5\33\3\0\3\33"+
    "\21\0\1\33\5\0\4\33\1\u0109\24\33\3\0\3\33"+
    "\21\0\1\33\5\0\23\33\1\u010a\5\33\3\0\3\33"+
    "\21\0\1\33\5\0\4\33\1\u010b\24\33\3\0\3\33"+
    "\21\0\1\33\5\0\16\33\1\u010c\12\33\3\0\3\33"+
    "\21\0\1\33\5\0\21\33\1\u010d\7\33\3\0\3\33"+
    "\21\0\1\33\5\0\1\u010e\30\33\3\0\3\33\21\0"+
    "\1\33\5\0\21\33\1\u010f\7\33\3\0\3\33\21\0"+
    "\1\33\5\0\23\33\1\u0110\5\33\3\0\3\33\21\0"+
    "\1\33\5\0\10\33\1\u0111\20\33\3\0\3\33\21\0"+
    "\1\33\5\0\16\33\1\u0112\12\33\3\0\3\33\21\0"+
    "\1\33\5\0\15\33\1\u0113\13\33\3\0\3\33\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[10800];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\2\1\1\11\1\1\2\11"+
    "\1\1\2\11\1\1\1\11\26\1\3\11\1\1\1\0"+
    "\1\11\1\1\2\0\3\11\3\0\3\11\56\1\1\0"+
    "\1\11\1\1\1\11\1\0\1\1\1\0\244\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[275];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public absScanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new token("ERROR", yytext(), yyline);
            }
          // fall through
          case 86: break;
          case 2:
            { /* Ignore */
            }
          // fall through
          case 87: break;
          case 3:
            { return new token("OP_OPENPARENTHESIS", yytext(), yyline);
            }
          // fall through
          case 88: break;
          case 4:
            { return new token("OR_CLOSEPARENTHESIS", yytext(), yyline);
            }
          // fall through
          case 89: break;
          case 5:
            { return new token("OP_MULT", yytext(), yyline);
            }
          // fall through
          case 90: break;
          case 6:
            { return new token("OP_SUM", yytext(), yyline);
            }
          // fall through
          case 91: break;
          case 7:
            { return new token("OP_COMMA", yytext(), yyline);
            }
          // fall through
          case 92: break;
          case 8:
            { return new token("OP_MINUS", yytext(), yyline);
            }
          // fall through
          case 93: break;
          case 9:
            { return new token("OP_PERIOD", yytext(), yyline);
            }
          // fall through
          case 94: break;
          case 10:
            { return new token("OP_SLASH", yytext(), yyline);
            }
          // fall through
          case 95: break;
          case 11:
            { return new token("NUMBER", yytext(), yyline);
            }
          // fall through
          case 96: break;
          case 12:
            { return new token("OP_COLON", yytext(), yyline);
            }
          // fall through
          case 97: break;
          case 13:
            { return new token("OP_SEMICOLON", yytext(), yyline);
            }
          // fall through
          case 98: break;
          case 14:
            { return new token("OP_LESS", yytext(), yyline);
            }
          // fall through
          case 99: break;
          case 15:
            { return new token("OP_EQUALS", yytext(), yyline);
            }
          // fall through
          case 100: break;
          case 16:
            { return new token("OP_GREATER", yytext(), yyline);
            }
          // fall through
          case 101: break;
          case 17:
            { return new token("IDENTIFIER", yytext(), yyline);
            }
          // fall through
          case 102: break;
          case 18:
            { return new token("OP_OPENBRACKET", yytext(), yyline);
            }
          // fall through
          case 103: break;
          case 19:
            { return new token("OP_CLOSEBRACKET", yytext(), yyline);
            }
          // fall through
          case 104: break;
          case 20:
            { return new token("OP_POWER", yytext(), yyline);
            }
          // fall through
          case 105: break;
          case 21:
            { return new token("LITERAL", yytext(), yyline);
            }
          // fall through
          case 106: break;
          case 22:
            { return new token("OP_DOUBLEASTERISK", yytext(), yyline);
            }
          // fall through
          case 107: break;
          case 23:
            { return new token("OP_INCREASE", yytext(), yyline);
            }
          // fall through
          case 108: break;
          case 24:
            { return new token("OP_DECREASE", yytext(), yyline);
            }
          // fall through
          case 109: break;
          case 25:
            { return new token("OP_LESSEQUAL", yytext(), yyline);
            }
          // fall through
          case 110: break;
          case 26:
            { return new token("OP_TYPE", yytext(), yyline);
            }
          // fall through
          case 111: break;
          case 27:
            { return new token("OP_GREATEREQUAL", yytext(), yyline);
            }
          // fall through
          case 112: break;
          case 28:
            { return new token("DO", yytext(), yyline);
            }
          // fall through
          case 113: break;
          case 29:
            { return new token("IF", yytext(), yyline);
            }
          // fall through
          case 114: break;
          case 30:
            { return new token("IN", yytext(), yyline);
            }
          // fall through
          case 115: break;
          case 31:
            { return new token("OF", yytext(), yyline);
            }
          // fall through
          case 116: break;
          case 32:
            { return new token("OR", yytext(), yyline);
            }
          // fall through
          case 117: break;
          case 33:
            { return new token("TO", yytext(), yyline);
            }
          // fall through
          case 118: break;
          case 34:
            { /* Inline comment */
            }
          // fall through
          case 119: break;
          case 35:
            { return new token("LITERAl", yytext(), yyline);
            }
          // fall through
          case 120: break;
          case 36:
            { return new token("AND", yytext(), yyline);
            }
          // fall through
          case 121: break;
          case 37:
            { return new token("ASM", yytext(), yyline);
            }
          // fall through
          case 122: break;
          case 38:
            { return new token("DIV", yytext(), yyline);
            }
          // fall through
          case 123: break;
          case 39:
            { return new token("END", yytext(), yyline);
            }
          // fall through
          case 124: break;
          case 40:
            { return new token("FOR", yytext(), yyline);
            }
          // fall through
          case 125: break;
          case 41:
            { return new token("INT", yytext(), yyline);
            }
          // fall through
          case 126: break;
          case 42:
            { return new token("MOD", yytext(), yyline);
            }
          // fall through
          case 127: break;
          case 43:
            { return new token("NIL", yytext(), yyline);
            }
          // fall through
          case 128: break;
          case 44:
            { return new token("NOT", yytext(), yyline);
            }
          // fall through
          case 129: break;
          case 45:
            { return new token("SET", yytext(), yyline);
            }
          // fall through
          case 130: break;
          case 46:
            { return new token("SHL", yytext(), yyline);
            }
          // fall through
          case 131: break;
          case 47:
            { return new token("SHR", yytext(), yyline);
            }
          // fall through
          case 132: break;
          case 48:
            { return new token("VAR", yytext(), yyline);
            }
          // fall through
          case 133: break;
          case 49:
            { return new token("XOR", yytext(), yyline);
            }
          // fall through
          case 134: break;
          case 50:
            { /* Multiblock comment */
            }
          // fall through
          case 135: break;
          case 51:
            { return new token("CASE", yytext(), yyline);
            }
          // fall through
          case 136: break;
          case 52:
            { return new token("CHAR", yytext(), yyline);
            }
          // fall through
          case 137: break;
          case 53:
            { return new token("ELSE", yytext(), yyline);
            }
          // fall through
          case 138: break;
          case 54:
            { return new token("FILE", yytext(), yyline);
            }
          // fall through
          case 139: break;
          case 55:
            { return new token("GOTO", yytext(), yyline);
            }
          // fall through
          case 140: break;
          case 56:
            { return new token("THEN", yytext(), yyline);
            }
          // fall through
          case 141: break;
          case 57:
            { return new token("TYPE", yytext(), yyline);
            }
          // fall through
          case 142: break;
          case 58:
            { return new token("UNIT", yytext(), yyline);
            }
          // fall through
          case 143: break;
          case 59:
            { return new token("USES", yytext(), yyline);
            }
          // fall through
          case 144: break;
          case 60:
            { return new token("WHILE", yytext(), yyline);
            }
          // fall through
          case 145: break;
          case 61:
            { return new token("ARRAY", yytext(), yyline);
            }
          // fall through
          case 146: break;
          case 62:
            { return new token("BEGIN", yytext(), yyline);
            }
          // fall through
          case 147: break;
          case 63:
            { return new token("CONST", yytext(), yyline);
            }
          // fall through
          case 148: break;
          case 64:
            { return new token("BOOL", yytext(), yyline);
            }
          // fall through
          case 149: break;
          case 65:
            { return new token("LABEL", yytext(), yyline);
            }
          // fall through
          case 150: break;
          case 66:
            { return new token("UNTIL", yytext(), yyline);
            }
          // fall through
          case 151: break;
          case 67:
            { return new token("DOWNTO", yytext(), yyline);
            }
          // fall through
          case 152: break;
          case 68:
            { return new token("INLINE", yytext(), yyline);
            }
          // fall through
          case 153: break;
          case 69:
            { return new token("OBJECT", yytext(), yyline);
            }
          // fall through
          case 154: break;
          case 70:
            { return new token("PACKED", yytext(), yyline);
            }
          // fall through
          case 155: break;
          case 71:
            { return new token("RECORD", yytext(), yyline);
            }
          // fall through
          case 156: break;
          case 72:
            { return new token("REPEAT", yytext(), yyline);
            }
          // fall through
          case 157: break;
          case 73:
            { return new token("STRING", yytext(), yyline);
            }
          // fall through
          case 158: break;
          case 74:
            { return new token("FORWARD", yytext(), yyline);
            }
          // fall through
          case 159: break;
          case 75:
            { return new token("PRIVATE", yytext(), yyline);
            }
          // fall through
          case 160: break;
          case 76:
            { return new token("VIRTUAL", yytext(), yyline);
            }
          // fall through
          case 161: break;
          case 77:
            { return new token("ABSOLUTE", yytext(), yyline);
            }
          // fall through
          case 162: break;
          case 78:
            { return new token("EXTERNAL", yytext(), yyline);
            }
          // fall through
          case 163: break;
          case 79:
            { return new token("FUNCTION", yytext(), yyline);
            }
          // fall through
          case 164: break;
          case 80:
            { return new token("INTERFACE", yytext(), yyline);
            }
          // fall through
          case 165: break;
          case 81:
            { return new token("INTERRUPT", yytext(), yyline);
            }
          // fall through
          case 166: break;
          case 82:
            { return new token("PROCEDURE", yytext(), yyline);
            }
          // fall through
          case 167: break;
          case 83:
            { return new token("DESTRUCTOR", yytext(), yyline);
            }
          // fall through
          case 168: break;
          case 84:
            { return new token("CONSTRUCTOR", yytext(), yyline);
            }
          // fall through
          case 169: break;
          case 85:
            { return new token("IMPLEMENTATION", yytext(), yyline);
            }
          // fall through
          case 170: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
