// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lexer.flex

// Main code
import obj.token;
// This object will contain the token name and line where is located


@SuppressWarnings("fallthrough")
public class absScanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\0"+
    "\1\5\4\0\1\1\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\12\16\1\17\1\20\1\21\1\22"+
    "\1\23\2\0\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\44\1\55\1\0\1\56\1\57"+
    "\1\44\1\0\4\60\1\61\1\60\21\44\1\62\2\44"+
    "\1\63\1\0\1\64\7\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\25\21\1\22\1\23\1\24\1\1\1\0"+
    "\1\25\1\0\1\26\1\27\1\30\3\0\1\31\1\32"+
    "\1\33\13\21\1\34\10\21\1\35\1\21\1\36\5\21"+
    "\1\37\1\40\7\21\1\41\10\21\1\0\1\42\1\0"+
    "\1\13\1\0\2\13\1\21\1\43\1\21\1\44\6\21"+
    "\1\45\2\21\1\46\3\21\1\47\4\21\1\50\1\21"+
    "\1\51\1\52\1\53\6\21\1\54\1\55\1\56\6\21"+
    "\1\57\3\21\1\60\1\61\4\21\1\62\1\63\3\21"+
    "\1\64\1\21\1\65\3\21\1\66\13\21\1\67\1\70"+
    "\1\71\1\21\1\72\2\21\1\73\1\21\1\74\1\75"+
    "\1\21\1\76\3\21\1\77\5\21\1\100\7\21\1\101"+
    "\5\21\1\102\4\21\1\103\2\21\1\104\1\105\2\21"+
    "\1\106\1\107\1\110\5\21\1\111\4\21\1\112\1\21"+
    "\1\113\1\114\2\21\1\115\1\116\7\21\1\117\1\120"+
    "\1\121\1\21\1\122\1\21\1\123\3\21\1\124";

  private static int [] zzUnpackAction() {
    int [] result = new int[270];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\65\0\u0109\0\u013e"+
    "\0\65\0\u0173\0\65\0\65\0\u01a8\0\65\0\65\0\u01dd"+
    "\0\65\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6\0\u031b\0\u0350"+
    "\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459\0\u048e\0\u04c3\0\u04f8"+
    "\0\u052d\0\u0562\0\u0597\0\u05cc\0\u0601\0\u0636\0\u066b\0\65"+
    "\0\65\0\65\0\u06a0\0\237\0\65\0\u06d5\0\65\0\65"+
    "\0\65\0\u070a\0\u073f\0\u0774\0\65\0\65\0\65\0\u07a9"+
    "\0\u07de\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951"+
    "\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9"+
    "\0\u0b2e\0\u0b63\0\u0b98\0\u03ba\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c"+
    "\0\u0ca1\0\u0cd6\0\u0d0b\0\u03ba\0\u03ba\0\u0d40\0\u0d75\0\u0daa"+
    "\0\u0ddf\0\u0e14\0\u0e49\0\u0e7e\0\u03ba\0\u0eb3\0\u0ee8\0\u0f1d"+
    "\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u06a0\0\65\0\u105b"+
    "\0\u1090\0\u10c5\0\u10c5\0\u0774\0\u10fa\0\u03ba\0\u112f\0\u03ba"+
    "\0\u1164\0\u1199\0\u11ce\0\u1203\0\u1238\0\u126d\0\u03ba\0\u12a2"+
    "\0\u12d7\0\u03ba\0\u130c\0\u1341\0\u1376\0\u13ab\0\u13e0\0\u1415"+
    "\0\u144a\0\u147f\0\u14b4\0\u14e9\0\u03ba\0\u03ba\0\u03ba\0\u151e"+
    "\0\u1553\0\u1588\0\u15bd\0\u15f2\0\u1627\0\u03ba\0\u03ba\0\u03ba"+
    "\0\u165c\0\u1691\0\u16c6\0\u16fb\0\u1730\0\u1765\0\u03ba\0\u179a"+
    "\0\u17cf\0\u1804\0\u03ba\0\u06d5\0\u1839\0\u186e\0\u18a3\0\u18d8"+
    "\0\u03ba\0\u03ba\0\u190d\0\u1942\0\u1977\0\u03ba\0\u19ac\0\u03ba"+
    "\0\u19e1\0\u1a16\0\u1a4b\0\u03ba\0\u1a80\0\u1ab5\0\u1aea\0\u1b1f"+
    "\0\u1b54\0\u1b89\0\u1bbe\0\u1bf3\0\u1c28\0\u1c5d\0\u1c92\0\u03ba"+
    "\0\u03ba\0\u03ba\0\u1cc7\0\u03ba\0\u1cfc\0\u1d31\0\u03ba\0\u1d66"+
    "\0\u03ba\0\u03ba\0\u1d9b\0\u1dd0\0\u1e05\0\u1e3a\0\u1e6f\0\u03ba"+
    "\0\u1ea4\0\u1ed9\0\u1f0e\0\u1f43\0\u1f78\0\u03ba\0\u1fad\0\u1fe2"+
    "\0\u2017\0\u204c\0\u2081\0\u20b6\0\u20eb\0\u03ba\0\u2120\0\u2155"+
    "\0\u218a\0\u21bf\0\u21f4\0\u03ba\0\u2229\0\u225e\0\u2293\0\u22c8"+
    "\0\u03ba\0\u22fd\0\u2332\0\u03ba\0\u03ba\0\u2367\0\u239c\0\u03ba"+
    "\0\u03ba\0\u03ba\0\u23d1\0\u2406\0\u243b\0\u2470\0\u24a5\0\u03ba"+
    "\0\u24da\0\u250f\0\u2544\0\u2579\0\u03ba\0\u25ae\0\u03ba\0\u03ba"+
    "\0\u25e3\0\u2618\0\u03ba\0\u03ba\0\u264d\0\u2682\0\u26b7\0\u26ec"+
    "\0\u2721\0\u2756\0\u278b\0\u03ba\0\u03ba\0\u03ba\0\u27c0\0\u03ba"+
    "\0\u27f5\0\u03ba\0\u282a\0\u285f\0\u2894\0\u03ba";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[270];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\2\32\1\34\1\35\1\36"+
    "\1\37\1\40\1\32\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\32\1\50\1\51\1\52\3\32\1\53"+
    "\1\2\66\0\2\3\1\0\1\3\62\0\1\54\2\0"+
    "\1\55\10\0\1\54\5\0\31\54\3\0\3\54\12\0"+
    "\1\56\64\0\1\57\65\0\1\60\66\0\1\61\65\0"+
    "\1\62\1\0\1\15\11\0\1\63\22\0\1\64\5\0"+
    "\1\63\1\64\24\0\1\65\1\66\63\0\1\67\60\0"+
    "\1\32\5\0\1\32\1\70\13\32\1\71\3\32\1\72"+
    "\1\73\6\32\3\0\3\32\20\0\1\32\5\0\4\32"+
    "\1\74\11\32\1\75\12\32\3\0\3\32\20\0\1\32"+
    "\5\0\1\76\6\32\1\77\6\32\1\100\12\32\3\0"+
    "\3\32\20\0\1\32\5\0\4\32\1\101\3\32\1\102"+
    "\5\32\1\103\12\32\3\0\3\32\20\0\1\32\5\0"+
    "\13\32\1\104\1\32\1\105\11\32\1\106\1\32\3\0"+
    "\3\32\20\0\1\32\5\0\10\32\1\107\2\32\1\110"+
    "\2\32\1\111\5\32\1\112\4\32\3\0\3\32\20\0"+
    "\1\32\5\0\16\32\1\113\12\32\3\0\3\32\20\0"+
    "\1\32\5\0\31\32\3\0\3\32\20\0\1\32\5\0"+
    "\5\32\1\114\6\32\1\115\1\116\13\32\3\0\3\32"+
    "\20\0\1\32\5\0\1\117\30\32\3\0\3\32\20\0"+
    "\1\32\5\0\16\32\1\120\12\32\3\0\3\32\20\0"+
    "\1\32\5\0\10\32\1\121\5\32\1\122\12\32\3\0"+
    "\3\32\20\0\1\32\5\0\1\32\1\123\3\32\1\124"+
    "\13\32\1\125\7\32\3\0\3\32\20\0\1\32\5\0"+
    "\1\126\20\32\1\127\7\32\3\0\3\32\20\0\1\32"+
    "\5\0\4\32\1\130\24\32\3\0\3\32\20\0\1\32"+
    "\5\0\4\32\1\131\2\32\1\132\13\32\1\133\5\32"+
    "\3\0\3\32\20\0\1\32\5\0\7\32\1\134\6\32"+
    "\1\135\11\32\1\136\3\0\3\32\20\0\1\32\5\0"+
    "\15\32\1\137\4\32\1\140\6\32\3\0\3\32\20\0"+
    "\1\32\5\0\1\141\7\32\1\142\20\32\3\0\3\32"+
    "\20\0\1\32\5\0\7\32\1\143\1\144\20\32\3\0"+
    "\3\32\20\0\1\32\5\0\16\32\1\145\12\32\3\0"+
    "\3\32\2\0\64\146\1\147\2\56\3\0\3\56\1\150"+
    "\54\56\16\0\1\151\57\0\1\152\1\0\1\152\2\0"+
    "\1\153\64\0\1\154\5\0\6\154\26\0\2\154\21\0"+
    "\1\32\5\0\22\32\1\155\6\32\3\0\3\32\20\0"+
    "\1\32\5\0\3\32\1\156\25\32\3\0\3\32\20\0"+
    "\1\32\5\0\21\32\1\157\7\32\3\0\3\32\20\0"+
    "\1\32\5\0\14\32\1\160\14\32\3\0\3\32\20\0"+
    "\1\32\5\0\6\32\1\161\22\32\3\0\3\32\20\0"+
    "\1\32\5\0\16\32\1\162\12\32\3\0\3\32\20\0"+
    "\1\32\5\0\22\32\1\163\6\32\3\0\3\32\20\0"+
    "\1\32\5\0\1\164\30\32\3\0\3\32\20\0\1\32"+
    "\5\0\15\32\1\165\13\32\3\0\3\32\20\0\1\32"+
    "\5\0\22\32\1\166\6\32\3\0\3\32\20\0\1\32"+
    "\5\0\25\32\1\167\3\32\3\0\3\32\20\0\1\32"+
    "\5\0\26\32\1\170\2\32\3\0\3\32\20\0\1\32"+
    "\5\0\22\32\1\171\6\32\3\0\3\32\20\0\1\32"+
    "\5\0\3\32\1\172\25\32\3\0\3\32\20\0\1\32"+
    "\5\0\23\32\1\173\5\32\3\0\3\32\20\0\1\32"+
    "\5\0\13\32\1\174\15\32\3\0\3\32\20\0\1\32"+
    "\5\0\16\32\1\175\12\32\3\0\3\32\20\0\1\32"+
    "\5\0\21\32\1\176\7\32\3\0\3\32\20\0\1\32"+
    "\5\0\15\32\1\177\13\32\3\0\3\32\20\0\1\32"+
    "\5\0\23\32\1\200\5\32\3\0\3\32\20\0\1\32"+
    "\5\0\17\32\1\201\11\32\3\0\3\32\20\0\1\32"+
    "\5\0\13\32\1\202\7\32\1\203\5\32\3\0\3\32"+
    "\20\0\1\32\5\0\1\32\1\204\27\32\3\0\3\32"+
    "\20\0\1\32\5\0\3\32\1\205\25\32\3\0\3\32"+
    "\20\0\1\32\5\0\13\32\1\206\15\32\3\0\3\32"+
    "\20\0\1\32\5\0\23\32\1\207\5\32\3\0\3\32"+
    "\20\0\1\32\5\0\11\32\1\210\17\32\3\0\3\32"+
    "\20\0\1\32\5\0\2\32\1\211\26\32\3\0\3\32"+
    "\20\0\1\32\5\0\10\32\1\212\5\32\1\213\12\32"+
    "\3\0\3\32\20\0\1\32\5\0\2\32\1\214\14\32"+
    "\1\215\11\32\3\0\3\32\20\0\1\32\5\0\23\32"+
    "\1\216\5\32\3\0\3\32\20\0\1\32\5\0\13\32"+
    "\1\217\5\32\1\220\7\32\3\0\3\32\20\0\1\32"+
    "\5\0\21\32\1\221\7\32\3\0\3\32\20\0\1\32"+
    "\5\0\4\32\1\222\24\32\3\0\3\32\20\0\1\32"+
    "\5\0\17\32\1\223\11\32\3\0\3\32\20\0\1\32"+
    "\5\0\10\32\1\224\12\32\1\225\5\32\3\0\3\32"+
    "\20\0\1\32\5\0\4\32\1\226\24\32\3\0\3\32"+
    "\20\0\1\32\5\0\21\32\1\227\7\32\3\0\3\32"+
    "\20\0\1\32\5\0\21\32\1\230\7\32\3\0\3\32"+
    "\20\0\1\32\5\0\10\32\1\231\20\32\3\0\3\32"+
    "\20\0\1\32\5\0\23\32\1\232\5\32\3\0\3\32"+
    "\20\0\1\32\5\0\21\32\1\233\7\32\3\0\3\32"+
    "\2\0\2\56\3\0\2\56\1\234\1\150\54\56\16\0"+
    "\1\151\11\0\1\63\30\0\1\63\21\0\1\153\64\0"+
    "\1\32\5\0\16\32\1\235\12\32\3\0\3\32\20\0"+
    "\1\32\5\0\1\236\30\32\3\0\3\32\20\0\1\32"+
    "\5\0\10\32\1\237\20\32\3\0\3\32\20\0\1\32"+
    "\5\0\13\32\1\240\15\32\3\0\3\32\20\0\1\32"+
    "\5\0\4\32\1\241\24\32\3\0\3\32\20\0\1\32"+
    "\5\0\21\32\1\242\7\32\3\0\3\32\20\0\1\32"+
    "\5\0\22\32\1\243\6\32\3\0\3\32\20\0\1\32"+
    "\5\0\23\32\1\244\5\32\3\0\3\32\20\0\1\32"+
    "\5\0\15\32\1\245\13\32\3\0\3\32\20\0\1\32"+
    "\5\0\4\32\1\246\24\32\3\0\3\32\20\0\1\32"+
    "\5\0\4\32\1\247\24\32\3\0\3\32\20\0\1\32"+
    "\5\0\4\32\1\250\24\32\3\0\3\32\20\0\1\32"+
    "\5\0\1\251\30\32\3\0\3\32\20\0\1\32\5\0"+
    "\26\32\1\252\2\32\3\0\3\32\20\0\1\32\5\0"+
    "\2\32\1\253\26\32\3\0\3\32\20\0\1\32\5\0"+
    "\16\32\1\254\12\32\3\0\3\32\20\0\1\32\5\0"+
    "\13\32\1\255\15\32\3\0\3\32\20\0\1\32\5\0"+
    "\10\32\1\256\20\32\3\0\3\32\20\0\1\32\5\0"+
    "\4\32\1\257\24\32\3\0\3\32\20\0\1\32\5\0"+
    "\4\32\1\260\24\32\3\0\3\32\20\0\1\32\5\0"+
    "\4\32\1\261\24\32\3\0\3\32\20\0\1\32\5\0"+
    "\12\32\1\262\16\32\3\0\3\32\20\0\1\32\5\0"+
    "\25\32\1\263\3\32\3\0\3\32\20\0\1\32\5\0"+
    "\2\32\1\264\26\32\3\0\3\32\20\0\1\32\5\0"+
    "\16\32\1\265\12\32\3\0\3\32\20\0\1\32\5\0"+
    "\4\32\1\266\24\32\3\0\3\32\20\0\1\32\5\0"+
    "\10\32\1\267\20\32\3\0\3\32\20\0\1\32\5\0"+
    "\15\32\1\270\13\32\3\0\3\32\20\0\1\32\5\0"+
    "\4\32\1\271\24\32\3\0\3\32\20\0\1\32\5\0"+
    "\23\32\1\272\5\32\3\0\3\32\20\0\1\32\5\0"+
    "\10\32\1\273\20\32\3\0\3\32\20\0\1\32\5\0"+
    "\22\32\1\274\6\32\3\0\3\32\20\0\1\32\5\0"+
    "\23\32\1\275\5\32\3\0\3\32\20\0\1\32\5\0"+
    "\13\32\1\276\15\32\3\0\3\32\20\0\1\32\5\0"+
    "\7\32\1\277\21\32\3\0\3\32\20\0\1\32\5\0"+
    "\13\32\1\300\15\32\3\0\3\32\20\0\1\32\5\0"+
    "\30\32\1\301\3\0\3\32\20\0\1\32\5\0\15\32"+
    "\1\302\13\32\3\0\3\32\20\0\1\32\5\0\4\32"+
    "\1\303\24\32\3\0\3\32\20\0\1\32\5\0\23\32"+
    "\1\304\5\32\3\0\3\32\20\0\1\32\5\0\21\32"+
    "\1\305\7\32\3\0\3\32\20\0\1\32\5\0\23\32"+
    "\1\306\5\32\3\0\3\32\20\0\1\32\5\0\21\32"+
    "\1\307\7\32\3\0\3\32\20\0\1\32\5\0\23\32"+
    "\1\310\5\32\3\0\3\32\20\0\1\32\5\0\1\311"+
    "\30\32\3\0\3\32\20\0\1\32\5\0\23\32\1\312"+
    "\5\32\3\0\3\32\20\0\1\32\5\0\4\32\1\313"+
    "\24\32\3\0\3\32\20\0\1\32\5\0\15\32\1\314"+
    "\13\32\3\0\3\32\20\0\1\32\5\0\21\32\1\315"+
    "\7\32\3\0\3\32\20\0\1\32\5\0\13\32\1\316"+
    "\15\32\3\0\3\32\20\0\1\32\5\0\2\32\1\317"+
    "\26\32\3\0\3\32\20\0\1\32\5\0\4\32\1\320"+
    "\24\32\3\0\3\32\20\0\1\32\5\0\1\321\30\32"+
    "\3\0\3\32\20\0\1\32\5\0\4\32\1\322\24\32"+
    "\3\0\3\32\20\0\1\32\5\0\21\32\1\323\7\32"+
    "\3\0\3\32\20\0\1\32\5\0\1\324\30\32\3\0"+
    "\3\32\20\0\1\32\5\0\15\32\1\325\13\32\3\0"+
    "\3\32\20\0\1\32\5\0\13\32\1\326\15\32\3\0"+
    "\3\32\20\0\1\32\5\0\24\32\1\327\4\32\3\0"+
    "\3\32\20\0\1\32\5\0\4\32\1\277\24\32\3\0"+
    "\3\32\20\0\1\32\5\0\24\32\1\330\4\32\3\0"+
    "\3\32\20\0\1\32\5\0\1\331\30\32\3\0\3\32"+
    "\20\0\1\32\5\0\21\32\1\332\7\32\3\0\3\32"+
    "\20\0\1\32\5\0\24\32\1\333\4\32\3\0\3\32"+
    "\20\0\1\32\5\0\16\32\1\334\12\32\3\0\3\32"+
    "\20\0\1\32\5\0\15\32\1\335\13\32\3\0\3\32"+
    "\20\0\1\32\5\0\21\32\1\336\7\32\3\0\3\32"+
    "\20\0\1\32\5\0\10\32\1\337\20\32\3\0\3\32"+
    "\20\0\1\32\5\0\14\32\1\340\14\32\3\0\3\32"+
    "\20\0\1\32\5\0\4\32\1\341\24\32\3\0\3\32"+
    "\20\0\1\32\5\0\5\32\1\342\13\32\1\343\7\32"+
    "\3\0\3\32\20\0\1\32\5\0\23\32\1\344\5\32"+
    "\3\0\3\32\20\0\1\32\5\0\3\32\1\345\25\32"+
    "\3\0\3\32\20\0\1\32\5\0\23\32\1\346\5\32"+
    "\3\0\3\32\20\0\1\32\5\0\3\32\1\347\25\32"+
    "\3\0\3\32\20\0\1\32\5\0\3\32\1\350\25\32"+
    "\3\0\3\32\20\0\1\32\5\0\23\32\1\351\5\32"+
    "\3\0\3\32\20\0\1\32\5\0\6\32\1\352\22\32"+
    "\3\0\3\32\20\0\1\32\5\0\1\353\30\32\3\0"+
    "\3\32\20\0\1\32\5\0\23\32\1\354\5\32\3\0"+
    "\3\32\20\0\1\32\5\0\15\32\1\310\13\32\3\0"+
    "\3\32\20\0\1\32\5\0\24\32\1\355\4\32\3\0"+
    "\3\32\20\0\1\32\5\0\2\32\1\356\26\32\3\0"+
    "\3\32\20\0\1\32\5\0\1\357\30\32\3\0\3\32"+
    "\20\0\1\32\5\0\3\32\1\360\25\32\3\0\3\32"+
    "\20\0\1\32\5\0\16\32\1\361\12\32\3\0\3\32"+
    "\20\0\1\32\5\0\4\32\1\362\24\32\3\0\3\32"+
    "\20\0\1\32\5\0\1\363\30\32\3\0\3\32\20\0"+
    "\1\32\5\0\24\32\1\364\4\32\3\0\3\32\20\0"+
    "\1\32\5\0\4\32\1\365\24\32\3\0\3\32\20\0"+
    "\1\32\5\0\24\32\1\366\4\32\3\0\3\32\20\0"+
    "\1\32\5\0\13\32\1\367\15\32\3\0\3\32\20\0"+
    "\1\32\5\0\4\32\1\370\24\32\3\0\3\32\20\0"+
    "\1\32\5\0\2\32\1\371\26\32\3\0\3\32\20\0"+
    "\1\32\5\0\23\32\1\372\5\32\3\0\3\32\20\0"+
    "\1\32\5\0\13\32\1\373\15\32\3\0\3\32\20\0"+
    "\1\32\5\0\15\32\1\374\13\32\3\0\3\32\20\0"+
    "\1\32\5\0\15\32\1\375\13\32\3\0\3\32\20\0"+
    "\1\32\5\0\2\32\1\376\26\32\3\0\3\32\20\0"+
    "\1\32\5\0\17\32\1\377\11\32\3\0\3\32\20\0"+
    "\1\32\5\0\21\32\1\u0100\7\32\3\0\3\32\20\0"+
    "\1\32\5\0\23\32\1\u0101\5\32\3\0\3\32\20\0"+
    "\1\32\5\0\16\32\1\u0102\12\32\3\0\3\32\20\0"+
    "\1\32\5\0\23\32\1\u0103\5\32\3\0\3\32\20\0"+
    "\1\32\5\0\4\32\1\u0104\24\32\3\0\3\32\20\0"+
    "\1\32\5\0\23\32\1\u0105\5\32\3\0\3\32\20\0"+
    "\1\32\5\0\4\32\1\u0106\24\32\3\0\3\32\20\0"+
    "\1\32\5\0\16\32\1\u0107\12\32\3\0\3\32\20\0"+
    "\1\32\5\0\21\32\1\u0108\7\32\3\0\3\32\20\0"+
    "\1\32\5\0\1\u0109\30\32\3\0\3\32\20\0\1\32"+
    "\5\0\21\32\1\u010a\7\32\3\0\3\32\20\0\1\32"+
    "\5\0\23\32\1\u010b\5\32\3\0\3\32\20\0\1\32"+
    "\5\0\10\32\1\u010c\20\32\3\0\3\32\20\0\1\32"+
    "\5\0\16\32\1\u010d\12\32\3\0\3\32\20\0\1\32"+
    "\5\0\15\32\1\u010e\13\32\3\0\3\32\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[10441];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\1\11\1\1\2\11"+
    "\1\1\2\11\1\1\1\11\26\1\3\11\1\1\1\0"+
    "\1\11\1\0\3\11\3\0\3\11\56\1\1\0\1\11"+
    "\1\0\1\1\1\0\244\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[270];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public absScanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new token("ERROR", yytext(), yyline);
            }
          // fall through
          case 85: break;
          case 2:
            { /* Ignore */
            }
          // fall through
          case 86: break;
          case 3:
            { return new token("OP_OPENPARENTHESIS", yytext(), yyline);
            }
          // fall through
          case 87: break;
          case 4:
            { return new token("OR_CLOSEPARENTHESIS", yytext(), yyline);
            }
          // fall through
          case 88: break;
          case 5:
            { return new token("OP_MULT", yytext(), yyline);
            }
          // fall through
          case 89: break;
          case 6:
            { return new token("OP_SUM", yytext(), yyline);
            }
          // fall through
          case 90: break;
          case 7:
            { return new token("OP_COMMA", yytext(), yyline);
            }
          // fall through
          case 91: break;
          case 8:
            { return new token("OP_MINUS", yytext(), yyline);
            }
          // fall through
          case 92: break;
          case 9:
            { return new token("OP_PERIOD", yytext(), yyline);
            }
          // fall through
          case 93: break;
          case 10:
            { return new token("OP_SLASH", yytext(), yyline);
            }
          // fall through
          case 94: break;
          case 11:
            { return new token("NUMBER", yytext(), yyline);
            }
          // fall through
          case 95: break;
          case 12:
            { return new token("OP_COLON", yytext(), yyline);
            }
          // fall through
          case 96: break;
          case 13:
            { return new token("OP_SEMICOLON", yytext(), yyline);
            }
          // fall through
          case 97: break;
          case 14:
            { return new token("OP_LESS", yytext(), yyline);
            }
          // fall through
          case 98: break;
          case 15:
            { return new token("OP_EQUALS", yytext(), yyline);
            }
          // fall through
          case 99: break;
          case 16:
            { return new token("OP_GREATER", yytext(), yyline);
            }
          // fall through
          case 100: break;
          case 17:
            { return new token("IDENTIFIER", yytext(), yyline);
            }
          // fall through
          case 101: break;
          case 18:
            { return new token("OP_OPENBRACKET", yytext(), yyline);
            }
          // fall through
          case 102: break;
          case 19:
            { return new token("OP_CLOSEBRACKET", yytext(), yyline);
            }
          // fall through
          case 103: break;
          case 20:
            { return new token("OP_POWER", yytext(), yyline);
            }
          // fall through
          case 104: break;
          case 21:
            { return new token("LITERAL", yytext(), yyline);
            }
          // fall through
          case 105: break;
          case 22:
            { return new token("OP_DOUBLEASTERISK", yytext(), yyline);
            }
          // fall through
          case 106: break;
          case 23:
            { return new token("OP_INCREASE", yytext(), yyline);
            }
          // fall through
          case 107: break;
          case 24:
            { return new token("OP_DECREASE", yytext(), yyline);
            }
          // fall through
          case 108: break;
          case 25:
            { return new token("OP_LESSEQUAL", yytext(), yyline);
            }
          // fall through
          case 109: break;
          case 26:
            { return new token("OP_TYPE", yytext(), yyline);
            }
          // fall through
          case 110: break;
          case 27:
            { return new token("OP_GREATEREQUAL", yytext(), yyline);
            }
          // fall through
          case 111: break;
          case 28:
            { return new token("DO", yytext(), yyline);
            }
          // fall through
          case 112: break;
          case 29:
            { return new token("IF", yytext(), yyline);
            }
          // fall through
          case 113: break;
          case 30:
            { return new token("IN", yytext(), yyline);
            }
          // fall through
          case 114: break;
          case 31:
            { return new token("OF", yytext(), yyline);
            }
          // fall through
          case 115: break;
          case 32:
            { return new token("OR", yytext(), yyline);
            }
          // fall through
          case 116: break;
          case 33:
            { return new token("TO", yytext(), yyline);
            }
          // fall through
          case 117: break;
          case 34:
            { /* Inline comment */
            }
          // fall through
          case 118: break;
          case 35:
            { return new token("AND", yytext(), yyline);
            }
          // fall through
          case 119: break;
          case 36:
            { return new token("ASM", yytext(), yyline);
            }
          // fall through
          case 120: break;
          case 37:
            { return new token("DIV", yytext(), yyline);
            }
          // fall through
          case 121: break;
          case 38:
            { return new token("END", yytext(), yyline);
            }
          // fall through
          case 122: break;
          case 39:
            { return new token("FOR", yytext(), yyline);
            }
          // fall through
          case 123: break;
          case 40:
            { return new token("INT", yytext(), yyline);
            }
          // fall through
          case 124: break;
          case 41:
            { return new token("MOD", yytext(), yyline);
            }
          // fall through
          case 125: break;
          case 42:
            { return new token("NIL", yytext(), yyline);
            }
          // fall through
          case 126: break;
          case 43:
            { return new token("NOT", yytext(), yyline);
            }
          // fall through
          case 127: break;
          case 44:
            { return new token("SET", yytext(), yyline);
            }
          // fall through
          case 128: break;
          case 45:
            { return new token("SHL", yytext(), yyline);
            }
          // fall through
          case 129: break;
          case 46:
            { return new token("SHR", yytext(), yyline);
            }
          // fall through
          case 130: break;
          case 47:
            { return new token("VAR", yytext(), yyline);
            }
          // fall through
          case 131: break;
          case 48:
            { return new token("XOR", yytext(), yyline);
            }
          // fall through
          case 132: break;
          case 49:
            { /* Multiblock comment */
            }
          // fall through
          case 133: break;
          case 50:
            { return new token("CASE", yytext(), yyline);
            }
          // fall through
          case 134: break;
          case 51:
            { return new token("CHAR", yytext(), yyline);
            }
          // fall through
          case 135: break;
          case 52:
            { return new token("ELSE", yytext(), yyline);
            }
          // fall through
          case 136: break;
          case 53:
            { return new token("FILE", yytext(), yyline);
            }
          // fall through
          case 137: break;
          case 54:
            { return new token("GOTO", yytext(), yyline);
            }
          // fall through
          case 138: break;
          case 55:
            { return new token("THEN", yytext(), yyline);
            }
          // fall through
          case 139: break;
          case 56:
            { return new token("TYPE", yytext(), yyline);
            }
          // fall through
          case 140: break;
          case 57:
            { return new token("UNIT", yytext(), yyline);
            }
          // fall through
          case 141: break;
          case 58:
            { return new token("USES", yytext(), yyline);
            }
          // fall through
          case 142: break;
          case 59:
            { return new token("WHILE", yytext(), yyline);
            }
          // fall through
          case 143: break;
          case 60:
            { return new token("ARRAY", yytext(), yyline);
            }
          // fall through
          case 144: break;
          case 61:
            { return new token("BEGIN", yytext(), yyline);
            }
          // fall through
          case 145: break;
          case 62:
            { return new token("CONST", yytext(), yyline);
            }
          // fall through
          case 146: break;
          case 63:
            { return new token("BOOL", yytext(), yyline);
            }
          // fall through
          case 147: break;
          case 64:
            { return new token("LABEL", yytext(), yyline);
            }
          // fall through
          case 148: break;
          case 65:
            { return new token("UNTIL", yytext(), yyline);
            }
          // fall through
          case 149: break;
          case 66:
            { return new token("DOWNTO", yytext(), yyline);
            }
          // fall through
          case 150: break;
          case 67:
            { return new token("INLINE", yytext(), yyline);
            }
          // fall through
          case 151: break;
          case 68:
            { return new token("OBJECT", yytext(), yyline);
            }
          // fall through
          case 152: break;
          case 69:
            { return new token("PACKED", yytext(), yyline);
            }
          // fall through
          case 153: break;
          case 70:
            { return new token("RECORD", yytext(), yyline);
            }
          // fall through
          case 154: break;
          case 71:
            { return new token("REPEAT", yytext(), yyline);
            }
          // fall through
          case 155: break;
          case 72:
            { return new token("STRING", yytext(), yyline);
            }
          // fall through
          case 156: break;
          case 73:
            { return new token("FORWARD", yytext(), yyline);
            }
          // fall through
          case 157: break;
          case 74:
            { return new token("PRIVATE", yytext(), yyline);
            }
          // fall through
          case 158: break;
          case 75:
            { return new token("VIRTUAL", yytext(), yyline);
            }
          // fall through
          case 159: break;
          case 76:
            { return new token("ABSOLUTE", yytext(), yyline);
            }
          // fall through
          case 160: break;
          case 77:
            { return new token("EXTERNAL", yytext(), yyline);
            }
          // fall through
          case 161: break;
          case 78:
            { return new token("FUNCTION", yytext(), yyline);
            }
          // fall through
          case 162: break;
          case 79:
            { return new token("INTERFACE", yytext(), yyline);
            }
          // fall through
          case 163: break;
          case 80:
            { return new token("INTERRUPT", yytext(), yyline);
            }
          // fall through
          case 164: break;
          case 81:
            { return new token("PROCEDURE", yytext(), yyline);
            }
          // fall through
          case 165: break;
          case 82:
            { return new token("DESTRUCTOR", yytext(), yyline);
            }
          // fall through
          case 166: break;
          case 83:
            { return new token("CONSTRUCTOR", yytext(), yyline);
            }
          // fall through
          case 167: break;
          case 84:
            { return new token("IMPLEMENTATION", yytext(), yyline);
            }
          // fall through
          case 168: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
