// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lexer.flex

// Main code
package scanner;
import java_cup.runtime.Symbol;
import parser.sym;
import java.util.ArrayList;


@SuppressWarnings("fallthrough")
public class absScanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\267\u0200\10\u0400\36\u0200\1\u0500"+
    "\u1001\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\4\1\0"+
    "\1\5\4\0\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\7\20\2\21\1\22\1\23"+
    "\1\24\1\25\1\26\2\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\2\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\40\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\2\40\1\55\1\0\1\56\1\57"+
    "\1\40\1\0\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\2\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\40\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\2\40\1\60\1\0\1\61\7\0\1\3\32\0"+
    "\1\1\217\0\2\62\115\0\1\63\u0187\0\1\1\40\0"+
    "\2\3\5\0\1\1\320\0\u0100\3\377\0\1\1";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\2\13\1\14\1\15\1\16"+
    "\1\17\1\20\21\21\1\22\1\23\1\24\3\1\1\0"+
    "\1\25\2\0\1\26\1\27\1\0\1\30\2\0\1\31"+
    "\1\32\1\33\1\34\5\21\1\35\1\0\4\21\1\36"+
    "\3\21\1\37\4\21\1\40\3\21\1\0\1\2\1\36"+
    "\2\0\1\41\1\0\1\13\1\0\1\13\1\42\1\21"+
    "\1\43\2\21\2\44\1\21\1\0\1\45\1\46\1\21"+
    "\1\47\1\50\1\51\4\21\1\52\1\21\1\0\1\21"+
    "\1\0\1\47\1\0\1\2\2\21\1\0\1\53\2\54"+
    "\3\21\1\55\1\56\1\21\1\0\1\57\1\21\1\0"+
    "\1\21\1\0\1\21\2\60\4\21\1\0\2\61\2\62"+
    "\2\21\1\0\2\21\2\63\2\21\1\0\1\21\1\64"+
    "\1\21\2\65\2\21\1\66\166\21";

  private static int [] zzUnpackAction() {
    int [] result = new int[284];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\64\0\64"+
    "\0\u0138\0\64\0\u016c\0\64\0\64\0\u01a0\0\u01d4\0\u0208"+
    "\0\64\0\u023c\0\64\0\u0270\0\u02a4\0\u02d8\0\u030c\0\u0340"+
    "\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444\0\u0478\0\u04ac\0\u04e0"+
    "\0\u0514\0\u0548\0\u057c\0\u05b0\0\u05e4\0\64\0\64\0\64"+
    "\0\u0618\0\u064c\0\u0680\0\234\0\64\0\u06b4\0\u06e8\0\64"+
    "\0\64\0\u071c\0\u0750\0\u0784\0\u07b8\0\64\0\64\0\64"+
    "\0\64\0\u07ec\0\u0820\0\u0854\0\u0888\0\u08bc\0\u07ec\0\u08f0"+
    "\0\u0924\0\u0958\0\u098c\0\u09c0\0\u07ec\0\u09f4\0\u0a28\0\u0a5c"+
    "\0\u07ec\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u07ec\0\u0b60\0\u0b94"+
    "\0\u0bc8\0\u0618\0\u0618\0\64\0\u0bfc\0\u0c30\0\64\0\u0c64"+
    "\0\u0c98\0\u0ccc\0\u0ccc\0\u07b8\0\u0d00\0\u0d00\0\u0d34\0\u0d68"+
    "\0\u0d00\0\64\0\u0d9c\0\u0dd0\0\u0d00\0\u0d00\0\u0e04\0\u0d00"+
    "\0\u0d00\0\u0d00\0\u0e38\0\u0e6c\0\u0ea0\0\u0ed4\0\u0d00\0\u0f08"+
    "\0\u0f3c\0\u0f70\0\u0fa4\0\64\0\u0fd8\0\u06e8\0\u100c\0\u1040"+
    "\0\u1074\0\u100c\0\u100c\0\64\0\u10a8\0\u10dc\0\u1110\0\u100c"+
    "\0\u100c\0\u1144\0\u1178\0\u100c\0\u11ac\0\u11e0\0\u1214\0\u1248"+
    "\0\u127c\0\u127c\0\64\0\u12b0\0\u12e4\0\u1318\0\u134c\0\u1380"+
    "\0\u127c\0\64\0\u127c\0\64\0\u13b4\0\u13e8\0\u141c\0\u1450"+
    "\0\u1484\0\u13b4\0\64\0\u14b8\0\u14ec\0\u1520\0\u1554\0\u14b8"+
    "\0\u1588\0\u1588\0\64\0\u15bc\0\u15f0\0\u15f0\0\u1624\0\u1658"+
    "\0\u168c\0\u16c0\0\u16f4\0\u1728\0\u175c\0\u1790\0\u17c4\0\u17f8"+
    "\0\u182c\0\u1860\0\u1894\0\u18c8\0\u18fc\0\u1930\0\u1964\0\u1998"+
    "\0\u19cc\0\u1a00\0\u1a34\0\u1a68\0\u1a9c\0\u1ad0\0\u1b04\0\u1b38"+
    "\0\u1b6c\0\u1ba0\0\u1bd4\0\u1c08\0\u1c3c\0\u1c70\0\u1ca4\0\u1cd8"+
    "\0\u1d0c\0\u1d40\0\u1d74\0\u1da8\0\u1ddc\0\u1e10\0\u1e44\0\u1e78"+
    "\0\u1eac\0\u1ee0\0\u1f14\0\u1f48\0\u1f7c\0\u1fb0\0\u1fe4\0\u2018"+
    "\0\u204c\0\u2080\0\u20b4\0\u20e8\0\u211c\0\u2150\0\u2184\0\u21b8"+
    "\0\u21ec\0\u2220\0\u2254\0\u2288\0\u22bc\0\u22f0\0\u2324\0\u2358"+
    "\0\u238c\0\u23c0\0\u23f4\0\u2428\0\u245c\0\u2490\0\u24c4\0\u24f8"+
    "\0\u252c\0\u2560\0\u2594\0\u25c8\0\u25fc\0\u2630\0\u2664\0\u2698"+
    "\0\u26cc\0\u2700\0\u2734\0\u2768\0\u279c\0\u27d0\0\u2804\0\u2838"+
    "\0\u286c\0\u28a0\0\u28d4\0\u2908\0\u293c\0\u2970\0\u29a4\0\u29d8"+
    "\0\u2a0c\0\u2a40\0\u2a74\0\u2aa8\0\u2adc\0\u2b10\0\u2b44\0\u2b78"+
    "\0\u2bac\0\u2be0\0\u2c14\0\u2c48\0\u2c7c\0\u2cb0\0\u2ce4\0\u2d18"+
    "\0\u2d4c\0\u2d80\0\u2db4\0\64";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[284];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\2\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\2\33\1\34\2\33\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\33\1\44\1\45"+
    "\1\33\1\46\1\47\1\50\1\51\1\2\1\52\1\53"+
    "\65\0\2\3\1\0\1\3\63\0\1\54\1\55\11\0"+
    "\3\54\5\0\26\54\13\0\1\56\12\0\3\56\5\0"+
    "\26\56\20\0\1\57\64\0\1\60\65\0\1\61\64\0"+
    "\1\62\1\0\2\63\1\17\11\0\1\64\20\0\1\65"+
    "\24\0\1\62\1\0\3\17\11\0\1\64\55\0\1\66"+
    "\63\0\1\67\1\70\62\0\1\71\55\0\3\72\5\0"+
    "\14\72\1\73\11\72\26\0\3\72\5\0\4\72\1\74"+
    "\21\72\26\0\3\72\5\0\7\72\1\75\16\72\26\0"+
    "\3\72\5\0\10\72\1\76\4\72\1\77\10\72\5\0"+
    "\1\100\20\0\3\72\5\0\12\72\1\101\1\72\1\102"+
    "\11\72\26\0\3\72\5\0\15\72\1\103\4\72\1\104"+
    "\3\72\26\0\3\72\5\0\26\72\26\0\3\72\5\0"+
    "\5\72\1\105\6\72\1\106\11\72\26\0\3\72\5\0"+
    "\15\72\1\107\10\72\26\0\3\72\5\0\15\72\1\110"+
    "\10\72\26\0\3\72\5\0\17\72\1\111\6\72\26\0"+
    "\3\72\5\0\17\72\1\112\6\72\26\0\3\72\5\0"+
    "\4\72\1\113\21\72\26\0\3\72\5\0\21\72\1\114"+
    "\4\72\26\0\3\72\5\0\7\72\1\115\5\72\1\116"+
    "\10\72\26\0\3\72\5\0\1\117\25\72\26\0\3\72"+
    "\5\0\7\72\1\120\7\72\1\121\6\72\7\0\61\122"+
    "\1\123\2\122\34\0\1\124\6\0\1\125\70\0\1\126"+
    "\21\0\1\127\55\0\2\57\2\0\5\57\1\130\52\57"+
    "\17\0\3\131\57\0\1\62\1\0\2\63\1\17\11\0"+
    "\1\64\42\0\1\132\1\0\1\132\2\0\3\133\61\0"+
    "\3\134\5\0\6\134\46\0\3\135\5\0\26\135\26\0"+
    "\3\135\5\0\3\135\1\136\22\135\26\0\3\135\5\0"+
    "\6\135\1\137\17\135\26\0\3\135\5\0\1\140\25\135"+
    "\26\0\3\135\5\0\23\135\1\141\2\135\61\0\1\142"+
    "\30\0\3\135\5\0\20\135\1\143\5\135\6\0\1\144"+
    "\17\0\3\135\5\0\3\135\1\145\22\135\26\0\3\135"+
    "\5\0\17\135\1\146\6\135\26\0\3\135\5\0\14\135"+
    "\1\147\11\135\26\0\3\135\5\0\21\135\1\150\4\135"+
    "\26\0\3\135\5\0\3\135\1\151\22\135\26\0\3\135"+
    "\5\0\21\135\1\152\4\135\26\0\3\135\5\0\15\135"+
    "\1\153\10\135\26\0\3\135\5\0\1\154\25\135\26\0"+
    "\3\135\5\0\17\135\1\155\6\135\26\0\3\135\5\0"+
    "\4\135\1\156\21\135\26\0\3\135\5\0\17\135\1\157"+
    "\6\135\26\0\3\135\5\0\10\135\1\160\15\135\5\0"+
    "\1\161\20\0\3\135\5\0\10\135\1\162\15\135\5\0"+
    "\1\163\51\0\1\164\61\0\1\165\15\0\2\57\2\0"+
    "\4\57\1\166\1\130\52\57\17\0\3\131\11\0\1\64"+
    "\47\0\3\133\61\0\3\167\5\0\26\167\26\0\3\167"+
    "\5\0\10\167\1\170\15\167\5\0\1\171\20\0\3\167"+
    "\5\0\17\167\1\172\6\167\26\0\3\167\5\0\4\167"+
    "\1\173\21\167\42\0\1\174\47\0\3\167\5\0\2\167"+
    "\1\175\23\167\26\0\3\167\5\0\2\167\1\176\3\167"+
    "\1\177\17\167\26\0\3\167\5\0\3\167\1\200\6\167"+
    "\1\201\13\167\26\0\3\167\5\0\10\167\1\202\15\167"+
    "\5\0\1\203\20\0\3\167\5\0\14\167\1\204\11\167"+
    "\26\0\3\167\5\0\12\167\1\205\13\167\50\0\1\206"+
    "\41\0\3\167\5\0\21\167\1\207\4\167\57\0\1\210"+
    "\52\0\1\203\22\0\1\203\20\0\3\211\5\0\26\211"+
    "\26\0\3\211\5\0\14\211\1\212\11\211\52\0\1\213"+
    "\37\0\3\211\5\0\21\211\1\214\4\211\26\0\3\211"+
    "\5\0\4\211\1\215\21\211\26\0\3\211\5\0\17\211"+
    "\1\216\6\211\26\0\3\211\5\0\14\211\1\217\11\211"+
    "\52\0\1\220\37\0\3\211\5\0\4\211\1\221\21\211"+
    "\42\0\1\222\47\0\3\211\5\0\4\211\1\223\21\211"+
    "\42\0\1\224\47\0\3\225\5\0\26\225\26\0\3\225"+
    "\5\0\10\225\1\226\15\225\5\0\1\227\20\0\3\225"+
    "\5\0\3\225\1\230\22\225\26\0\3\225\5\0\1\231"+
    "\25\225\26\0\3\225\5\0\6\225\1\232\17\225\44\0"+
    "\1\233\45\0\3\234\5\0\26\234\26\0\3\234\5\0"+
    "\15\234\1\235\10\234\53\0\1\236\36\0\3\234\5\0"+
    "\22\234\1\237\3\234\26\0\3\234\5\0\13\234\1\240"+
    "\12\234\26\0\3\241\5\0\26\241\26\0\3\241\5\0"+
    "\14\241\1\242\11\241\52\0\1\243\37\0\3\241\5\0"+
    "\17\241\1\244\6\241\26\0\3\245\5\0\26\245\26\0"+
    "\3\245\5\0\4\245\1\246\21\245\26\0\3\247\5\0"+
    "\26\247\26\0\3\250\5\0\26\250\26\0\3\251\5\0"+
    "\26\251\26\0\3\252\5\0\26\252\26\0\3\253\5\0"+
    "\26\253\26\0\3\254\5\0\26\254\26\0\3\255\5\0"+
    "\26\255\26\0\3\256\5\0\26\256\26\0\3\257\5\0"+
    "\26\257\26\0\3\260\5\0\26\260\26\0\3\261\5\0"+
    "\26\261\26\0\3\262\5\0\26\262\26\0\3\263\5\0"+
    "\26\263\26\0\3\264\5\0\26\264\26\0\3\265\5\0"+
    "\26\265\26\0\3\266\5\0\26\266\26\0\3\267\5\0"+
    "\26\267\26\0\3\270\5\0\26\270\26\0\3\271\5\0"+
    "\26\271\26\0\3\272\5\0\26\272\26\0\3\273\5\0"+
    "\26\273\26\0\3\274\5\0\26\274\26\0\3\275\5\0"+
    "\26\275\26\0\3\276\5\0\26\276\26\0\3\277\5\0"+
    "\26\277\26\0\3\300\5\0\26\300\26\0\3\301\5\0"+
    "\26\301\26\0\3\302\5\0\26\302\26\0\3\303\5\0"+
    "\26\303\26\0\3\304\5\0\26\304\26\0\3\305\5\0"+
    "\26\305\26\0\3\306\5\0\26\306\26\0\3\307\5\0"+
    "\26\307\26\0\3\310\5\0\26\310\26\0\3\311\5\0"+
    "\26\311\26\0\3\312\5\0\26\312\26\0\3\313\5\0"+
    "\26\313\26\0\3\314\5\0\26\314\26\0\3\315\5\0"+
    "\26\315\26\0\3\316\5\0\26\316\26\0\3\317\5\0"+
    "\26\317\26\0\3\320\5\0\26\320\26\0\3\321\5\0"+
    "\26\321\26\0\3\322\5\0\26\322\26\0\3\323\5\0"+
    "\26\323\26\0\3\324\5\0\26\324\26\0\3\325\5\0"+
    "\26\325\26\0\3\326\5\0\26\326\26\0\3\327\5\0"+
    "\26\327\26\0\3\330\5\0\26\330\26\0\3\331\5\0"+
    "\26\331\26\0\3\332\5\0\26\332\26\0\3\333\5\0"+
    "\26\333\26\0\3\334\5\0\26\334\26\0\3\335\5\0"+
    "\26\335\26\0\3\336\5\0\26\336\26\0\3\337\5\0"+
    "\26\337\26\0\3\340\5\0\26\340\26\0\3\341\5\0"+
    "\26\341\26\0\3\342\5\0\26\342\26\0\3\343\5\0"+
    "\26\343\26\0\3\344\5\0\26\344\26\0\3\345\5\0"+
    "\26\345\26\0\3\346\5\0\26\346\26\0\3\347\5\0"+
    "\26\347\26\0\3\350\5\0\26\350\26\0\3\351\5\0"+
    "\26\351\26\0\3\352\5\0\26\352\26\0\3\353\5\0"+
    "\26\353\26\0\3\354\5\0\26\354\26\0\3\355\5\0"+
    "\26\355\26\0\3\356\5\0\26\356\26\0\3\357\5\0"+
    "\26\357\26\0\3\360\5\0\26\360\26\0\3\361\5\0"+
    "\26\361\26\0\3\362\5\0\26\362\26\0\3\363\5\0"+
    "\26\363\26\0\3\364\5\0\26\364\26\0\3\365\5\0"+
    "\26\365\26\0\3\366\5\0\26\366\26\0\3\367\5\0"+
    "\26\367\26\0\3\370\5\0\26\370\26\0\3\371\5\0"+
    "\26\371\26\0\3\372\5\0\26\372\26\0\3\373\5\0"+
    "\26\373\26\0\3\374\5\0\26\374\26\0\3\375\5\0"+
    "\26\375\26\0\3\376\5\0\26\376\26\0\3\377\5\0"+
    "\26\377\26\0\3\u0100\5\0\26\u0100\26\0\3\u0101\5\0"+
    "\26\u0101\26\0\3\u0102\5\0\26\u0102\26\0\3\u0103\5\0"+
    "\26\u0103\26\0\3\u0104\5\0\26\u0104\26\0\3\u0105\5\0"+
    "\26\u0105\26\0\3\u0106\5\0\26\u0106\26\0\3\u0107\5\0"+
    "\26\u0107\26\0\3\u0108\5\0\26\u0108\26\0\3\u0109\5\0"+
    "\26\u0109\26\0\3\u010a\5\0\26\u010a\26\0\3\u010b\5\0"+
    "\26\u010b\26\0\3\u010c\5\0\26\u010c\26\0\3\u010d\5\0"+
    "\26\u010d\26\0\3\u010e\5\0\26\u010e\26\0\3\u010f\5\0"+
    "\26\u010f\26\0\3\u0110\5\0\26\u0110\26\0\3\u0111\5\0"+
    "\26\u0111\26\0\3\u0112\5\0\26\u0112\26\0\3\u0113\5\0"+
    "\26\u0113\26\0\3\u0114\5\0\26\u0114\26\0\3\u0115\5\0"+
    "\26\u0115\26\0\3\u0116\5\0\26\u0116\26\0\3\u0117\5\0"+
    "\26\u0117\26\0\3\u0118\5\0\26\u0118\26\0\3\u0119\5\0"+
    "\26\u0119\26\0\3\u011a\5\0\26\u011a\26\0\3\u011b\5\0"+
    "\26\u011b\26\0\3\u011c\5\0\26\u011c\7\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[11752];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\2\11\1\1\1\11\1\1\2\11"+
    "\3\1\1\11\1\1\1\11\22\1\3\11\3\1\1\0"+
    "\1\11\2\0\2\11\1\0\1\1\2\0\4\11\6\1"+
    "\1\0\21\1\1\0\1\1\1\11\2\0\1\11\1\0"+
    "\1\1\1\0\7\1\1\11\1\1\1\0\14\1\1\0"+
    "\1\1\1\0\1\11\1\0\3\1\1\0\2\1\1\11"+
    "\6\1\1\0\2\1\1\0\1\1\1\0\2\1\1\11"+
    "\4\1\1\0\1\1\1\11\1\1\1\11\2\1\1\0"+
    "\3\1\1\11\2\1\1\0\4\1\1\11\170\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[284];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
  public ArrayList<String> lexErrors = new ArrayList<>();
  // Here we will keep a list of the error that we'll find during the scanning

  /**
  * This fucntion creates a Symbol and then assign an ID, line and column
  * @param id
  * @return The Symbol with the information of said token
  */
  private Symbol sym(int id) {
      return new Symbol(id, yyline+1, yycolumn+1);
  }

  /**
  * This fucntion creates a Symbol and then assign an ID, line and column
  * @param id
  * @param val
  * @return The Symbol with the information of said token
  */
  private Symbol sym(int id, Object val) {
      return new Symbol(id, yyline+1, yycolumn+1, val);
  }

  /**
  * This fucntion creates a Symbol and then assign an ID, line and column
  * @param id
  * @param val
  * @param line
  * @param column
  * @return The Symbol with the information of said token
  */
  private Symbol symbol(int type, Object val, int line, int column) {
      return new Symbol(type, line, column, val);
  }

  /**
  * Ads the provided string to the list of errors that we will be displaying at the end of the compiling
  * @param msg
  */
  private void addLexError(String msg) {
      lexErrors.add("Línea " + (yyline + 1) + ", Columna " + (yycolumn + 1) + ": " + msg);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public absScanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { addLexError("Carácter no reconocido: '" + yytext() + "'");
          return sym(sym.ERROR, yytext());
            }
          // fall through
          case 55: break;
          case 2:
            { /* ignore */
            }
          // fall through
          case 56: break;
          case 3:
            { return sym(sym.LPAREN);
            }
          // fall through
          case 57: break;
          case 4:
            { return sym(sym.RPAREN);
            }
          // fall through
          case 58: break;
          case 5:
            { return sym(sym.TIMES);
            }
          // fall through
          case 59: break;
          case 6:
            { return sym(sym.PLUS);
            }
          // fall through
          case 60: break;
          case 7:
            { return sym(sym.COMMA);
            }
          // fall through
          case 61: break;
          case 8:
            { return sym(sym.MINUS);
            }
          // fall through
          case 62: break;
          case 9:
            { return sym(sym.DOT);
            }
          // fall through
          case 63: break;
          case 10:
            { return sym(sym.DIVIDE);
            }
          // fall through
          case 64: break;
          case 11:
            { String t = yytext();
          if (t.indexOf('.') >= 0 || t.indexOf('e')>=0 || t.indexOf('E')>=0)
              return sym(sym.REAL_LIT, t);
          else
              return sym(sym.INT_LIT, t);
            }
          // fall through
          case 65: break;
          case 12:
            { return sym(sym.COLON);
            }
          // fall through
          case 66: break;
          case 13:
            { return sym(sym.SEMI);
            }
          // fall through
          case 67: break;
          case 14:
            { return sym(sym.LT);
            }
          // fall through
          case 68: break;
          case 15:
            { return sym(sym.EQ);
            }
          // fall through
          case 69: break;
          case 16:
            { return sym(sym.GT);
            }
          // fall through
          case 70: break;
          case 17:
            { return sym(sym.ID, yytext());
            }
          // fall through
          case 71: break;
          case 18:
            { return sym(sym.LBRACK);
            }
          // fall through
          case 72: break;
          case 19:
            { return sym(sym.RBRACK);
            }
          // fall through
          case 73: break;
          case 20:
            { return sym(sym.CARET);
            }
          // fall through
          case 74: break;
          case 21:
            { return sym(sym.STR_LIT, yytext());
            }
          // fall through
          case 75: break;
          case 22:
            { return sym(sym.INC);
            }
          // fall through
          case 76: break;
          case 23:
            { return sym(sym.DEC);
            }
          // fall through
          case 77: break;
          case 24:
            { return sym(sym.INT_LIT, yytext());
            }
          // fall through
          case 78: break;
          case 25:
            { return sym(sym.ASSIGN);
            }
          // fall through
          case 79: break;
          case 26:
            { return sym(sym.LE);
            }
          // fall through
          case 80: break;
          case 27:
            { return sym(sym.NE);
            }
          // fall through
          case 81: break;
          case 28:
            { return sym(sym.GE);
            }
          // fall through
          case 82: break;
          case 29:
            { return sym(sym.DO);
            }
          // fall through
          case 83: break;
          case 30:
            { return sym(sym.IF);
            }
          // fall through
          case 84: break;
          case 31:
            { return sym(sym.OR);
            }
          // fall through
          case 85: break;
          case 32:
            { return sym(sym.TO);
            }
          // fall through
          case 86: break;
          case 33:
            { return sym(sym.CHAR_LIT, yytext());
            }
          // fall through
          case 87: break;
          case 34:
            { return sym(sym.HEX_LIT, yytext());
            }
          // fall through
          case 88: break;
          case 35:
            { return sym(sym.AND);
            }
          // fall through
          case 89: break;
          case 36:
            { return sym(sym.INTDIV);
            }
          // fall through
          case 90: break;
          case 37:
            { return sym(sym.END);
            }
          // fall through
          case 91: break;
          case 38:
            { return sym(sym.FOR);
            }
          // fall through
          case 92: break;
          case 39:
            { return sym(sym.TINT);
            }
          // fall through
          case 93: break;
          case 40:
            { return sym(sym.MOD);
            }
          // fall through
          case 94: break;
          case 41:
            { return sym(sym.NOT);
            }
          // fall through
          case 95: break;
          case 42:
            { return sym(sym.VAR);
            }
          // fall through
          case 96: break;
          case 43:
            { return sym(sym.TCHAR);
            }
          // fall through
          case 97: break;
          case 44:
            { return sym(sym.ELSE);
            }
          // fall through
          case 98: break;
          case 45:
            { return sym(sym.READ);
            }
          // fall through
          case 99: break;
          case 46:
            { return sym(sym.TREAL);
            }
          // fall through
          case 100: break;
          case 47:
            { return sym(sym.THEN);
            }
          // fall through
          case 101: break;
          case 48:
            { return sym(sym.BEGIN);
            }
          // fall through
          case 102: break;
          case 49:
            { return sym(sym.WHILE);
            }
          // fall through
          case 103: break;
          case 50:
            { return sym(sym.WRITE);
            }
          // fall through
          case 104: break;
          case 51:
            { return sym(sym.TSTRING);
            }
          // fall through
          case 105: break;
          case 52:
            { return sym(sym.PROGRAM);
            }
          // fall through
          case 106: break;
          case 53:
            { return sym(sym.FUNCTION);
            }
          // fall through
          case 107: break;
          case 54:
            { return sym(sym.PROCEDURE);
            }
          // fall through
          case 108: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
