
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_LIT = 53;
  public static final int DIVIDE = 27;
  public static final int FUNCTION = 6;
  public static final int TSTRING = 19;
  public static final int GE = 31;
  public static final int TCHAR = 20;
  public static final int UMINUS = 55;
  public static final int HEX_LIT = 51;
  public static final int SEMI = 44;
  public static final int LPAREN = 39;
  public static final int INTDIV = 29;
  public static final int FOR = 13;
  public static final int MINUS = 25;
  public static final int WRITE = 16;
  public static final int OCT_LIT = 54;
  public static final int RPAREN = 40;
  public static final int NOT = 38;
  public static final int AND = 37;
  public static final int LT = 34;
  public static final int OR = 36;
  public static final int COMMA = 43;
  public static final int INC = 22;
  public static final int BEGIN = 3;
  public static final int PLUS = 24;
  public static final int ASSIGN = 21;
  public static final int IF = 8;
  public static final int CARET = 47;
  public static final int ID = 48;
  public static final int DOT = 46;
  public static final int LE = 33;
  public static final int EOF = 0;
  public static final int KEYWORD = 56;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 28;
  public static final int STR_LIT = 52;
  public static final int EQ = 30;
  public static final int ERROR = 57;
  public static final int LBRACK = 41;
  public static final int TREAL = 18;
  public static final int TIMES = 26;
  public static final int COLON = 45;
  public static final int TINT = 17;
  public static final int ELSE = 10;
  public static final int RBRACK = 42;
  public static final int READ = 15;
  public static final int TO = 14;
  public static final int WHILE = 11;
  public static final int REAL_LIT = 50;
  public static final int THEN = 9;
  public static final int NE = 35;
  public static final int END = 4;
  public static final int DEC = 23;
  public static final int INT_LIT = 49;
  public static final int GT = 32;
  public static final int VAR = 5;
  public static final int PROCEDURE = 7;
  public static final int DO = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "BEGIN",
  "END",
  "VAR",
  "FUNCTION",
  "PROCEDURE",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "TO",
  "READ",
  "WRITE",
  "TINT",
  "TREAL",
  "TSTRING",
  "TCHAR",
  "ASSIGN",
  "INC",
  "DEC",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "INTDIV",
  "EQ",
  "GE",
  "GT",
  "LE",
  "LT",
  "NE",
  "OR",
  "AND",
  "NOT",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "COMMA",
  "SEMI",
  "COLON",
  "DOT",
  "CARET",
  "ID",
  "INT_LIT",
  "REAL_LIT",
  "HEX_LIT",
  "STR_LIT",
  "CHAR_LIT",
  "OCT_LIT",
  "UMINUS",
  "KEYWORD",
  "ERROR"
  };
}

